all:
  children:
    routers:
      hosts:
        r1:
          ansible_host: 10.10.10.1
        r2:
          ansible_host: 10.10.10.2
    switches:
      hosts:
        sw1:
          ansible_host: 10.10.20.1
        sw2:
          ansible_host: 10.10.20.2

    cisco:
      children:
        routers:
        switches:

